# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-25 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('episode', models.IntegerField()),
                ('company', models.CharField(max_length=140)),
                ('deal', models.CharField(max_length=140)),
                ('industry', models.CharField(max_length=140)),
                ('entrepreneur_gender', models.CharField(max_length=140)),
                ('amount', models.IntegerField(default=0)),
                ('equity', models.FloatField(default=0)),
                ('valuation', models.IntegerField(max_length=140)),
                ('corcoran', models.CharField(max_length=100)),
                ('cuban', models.CharField(max_length=100)),
                ('greiner', models.CharField(max_length=100)),
                ('herjavec', models.CharField(max_length=100)),
                ('john', models.CharField(max_length=100)),
                ('olary', models.CharField(max_length=100)),
                ('harrington', models.CharField(max_length=100)),
                ('guests', models.CharField(max_length=100)),
                ('no_of_sharks', models.IntegerField(default=0)),
                ('investPer_shark', models.IntegerField(default=0)),
                ('note', models.TextField()),
            ],
        ),
    ]
