# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-25 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stpdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='valuation',
            field=models.IntegerField(default=0),
        ),
    ]
