# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-25 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stpdata', '0003_auto_20180825_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='corcoran',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='cuban',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='deal',
            field=models.CharField(default=0, max_length=140),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='episode',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='equity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='greiner',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='guests',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='harrington',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='herjavec',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='investPer_shark',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='john',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='no_of_sharks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='note',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='olary',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='valuation',
            field=models.IntegerField(default=0),
        ),
    ]
